name: PyCerver Beta

on:
   push:
    branches:
      - '*beta'
      - '!main'

jobs:
  build:
    name: Build beta docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # docker setup
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # login
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # beta
      - name: Build beta image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.beta
          tags: ermiry/pycerver:beta
          push: true
